name = "default_eval"
metrics = ["sequence_similarity", "bleu", "chrf2++", "comet", "terminology_success_rate", "variant_aware_terminology_success_rate", "target_term_coverage", "variant_aware_target_term_coverage"]
terminology_groups = ["refined"]
comet_model = "Unbabel/wmt22-comet-da"
comet_batch_size = 8
comet_gpus = 0
